<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		<h3>async与await的错误处理</h3>
		<p>async返回的也是promise 所以也可以用catch()处理</p>
	</body>
	<script src="js/ajax.js"></script>
	<script>
		// 放外部
		// async function getGoods(){
		// 	return Request("/productlist")
		// }
		// getGoods().then(res=>{
		// 	console.log(res);
		// }).catch(err=>{
		// 	console.log(err);
		// })
		// 放内部
		async function getGoods() {
			try {
				return await Request("/productlist");
			} catch (err) {
				console.log(err.message);
			}
		}
		getGoods().then(res => {
			console.log(res);
		});
	</script>
</html>
